### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by MastaBaba** [uvdesk/uvdesk.github.io#41]
Downloading the UVDesk package, uploading it to my web server, then browsing to /public, generates a blank screen.

When I turn on all notices and errors, I get this (replacing {{installation-location}} for my installation location):

Fatal error: Uncaught Symfony\Component\Dotenv\Exception\PathException: Unable to read the "/{{installation-location}}/.env" environment file. in /{{installation-location}}/vendor/symfony/dotenv/Dotenv.php:567 Stack trace: #0 /{{installation-location}}/vendor/symfony/dotenv/Dotenv.php(114): Symfony\Component\Dotenv\Dotenv->doLoad(false, Array) #1 /{{installation-location}}/vendor/symfony/dotenv/Dotenv.php(157): Symfony\Component\Dotenv\Dotenv->loadEnv('/...', 'APP_ENV', 'dev', Array, false) #2 /{{installation-location}}/vendor/symfony/runtime/SymfonyRuntime.php(107): Symfony\Component\Dotenv\Dotenv->bootEnv('/...', 'dev', Array, false) #3 /{{installation-location}}/vendor/autoload_runtime.php(23): Symfony\Component\Runtime\SymfonyRuntime->__construct(Array) #4 /{{installation-location}}/public/index.php(9): require_once('/...') #5 {main} thrown in /{{installation-location}}/vendor/symfony/dotenv/Dotenv.php on line 567

**Comment by Komal-sharma-2712** [comment]
Let us know, you have followed this official uvdesk github page for downloading uvdesk opensource project:

[https://github.com/uvdesk/community-skeleton](https://github.com/uvdesk/community-skeleton) 

If yes, let us know you are using composer command or using zip file:

You can use **composer to setup your project** by simply running the following command from your terminal:

`$ composer create-project uvdesk/community-skeleton helpdesk-project`

**Direct Download**
Alternatively, you can also [download the zip archive](https://cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk-community-current-stable.zip) of the latest stable release and **extract its content** by running the following commands from your terminal:

Also, you can follow this **blog for installation guide**:
[https://www.uvdesk.com/en/blog/open-source-helpdesk-installation-on-windows-uvdesk/](https://www.uvdesk.com/en/blog/open-source-helpdesk-installation-on-windows-uvdesk/)

**Comment by MastaBaba** [comment]
Thanks. As I mentioned, I downloaded the archive and uploaded it to my server. I did not use composer.

**Comment by Komal-sharma-2712** [comment]
> Thanks. As I mentioned, I downloaded the archive and uploaded it to my server. I did not use composer.

Let us know, you have still facing the same error. Please, share a screenshots of the error.

**Comment by Komal-sharma-2712** [comment]
Can you please once try with the composer command. Also, let us know you are facing the same error using composer command.

You can use composer to setup your project by simply running the following command from your terminal:

`$ composer create-project uvdesk/community-skeleton helpdesk-project`

**Comment by MastaBaba** [comment]
I finally got around to trying out the composer, but this was a very painful exercise that eventually lead to nothing.

Eventually, I got this when running composer:

```
Problem 1
    - uvdesk/mailbox-component 1.2.x-dev is an alias of uvdesk/mailbox-component dev-master and thus requires it to be installed too.
    - uvdesk/mailbox-component[dev-master, v1.1.0, ..., 1.2.x-dev] require php-mime-mail-parser/php-mime-mail-parser ^7.0.0 -> satisfiable by php-mime-mail-parser/php-mime-mail-parser[7.0.0, 7.1.0, 7.1.1, 7.1.2].
    - php-mime-mail-parser/php-mime-mail-parser[7.0.0, ..., 7.1.2] require ext-mailparse * -> it is missing from your system. Install or enable PHP's mailparse extension.
    - Root composer.json requires uvdesk/mailbox-component ^1.1 -> satisfiable by uvdesk/mailbox-component[v1.1.0, ..., 1.2.x-dev (alias of dev-master)].
```

Installing mailbox component gave me this:

```
Problem 1
    - php-mime-mail-parser/php-mime-mail-parser[7.0.0, ..., 7.1.2] require ext-mailparse * -> it is missing from your system. Install or enable PHP's mailparse extension.
    - Root composer.json requires php-mime-mail-parser/php-mime-mail-parser ^7.0.0 -> satisfiable by php-mime-mail-parser/php-mime-mail-parser[7.0.0, 7.1.0, 7.1.1, 7.1.2].
```

I could not get to install the mail parser.  For example, the link at https://serverpilot.io/docs/how-to-install-the-php-mailparse-extension/ has no info on how to do this on PHP8.1.

**Comment by Komal-sharma-2712** [comment]
> Eventually, I got this when running composer:

This error shows due to php mailparse extension is not enabled.

**You can refer the below blog for the how to add php mailparse extension:**

https://webkul.com/blog/how-to-add-an-extension-imap-and-mailparse-on-windows-linux-mac/

**Comment by MastaBaba** [comment]
When doing this:

sudo apt-get install php8.1-imap

I get this:

```
E: Unable to locate package php8.1-imap
E: Couldn't find any package by glob 'php8.1-imap'
E: Couldn't find any package by regex 'php8.1-imap'
```
